
name: add-issues-to-project

description: Automatically add new issues to a project

inputs:
  gitub_token:
    description: Github API access token
    required: true
  github_project_title:
    description: Title of the project
    required: true
  github_org:
    description: The Github organization within which the project lives
    required: false
runs:
  using: node16
  main: dist/index.js
